# Reusable workflow for PHP syntax linting
#
# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Lint php

on:
  workflow_call:
    inputs:
      lint-command:
        description: 'Composer command to run lint'
        required: false
        type: string
        default: 'composer run lint'
      php-extensions:
        description: 'PHP extensions to install'
        required: false
        type: string
        default: 'bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite'

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      php-versions: ${{ steps.versions.outputs.php-versions }}
    steps:
      - name: Checkout app
        uses: actions/checkout@v4
      - name: Get version matrix
        id: versions
        uses: icewind1991/nextcloud-version-matrix@v1

  php-lint:
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix:
        php-versions: ${{fromJson(needs.matrix.outputs.php-versions)}}

    name: php-lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ inputs.php-extensions }}
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        run: ${{ inputs.lint-command }}

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: php-lint

    if: always()

    name: php-lint-summary

    steps:
      - name: Summary status
        run: if ${{ needs.php-lint.result != 'success' && needs.php-lint.result != 'skipped' }}; then exit 1; fi
