# Reusable workflow for PHP code style linting
#
# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Lint php-cs

on:
  workflow_call:
    inputs:
      cs-check-command:
        description: 'Composer command to check code style'
        required: false
        type: string
        default: "composer run cs:check || ( echo 'Please run `composer run cs:fix` to format your code' && exit 1 )"
      php-extensions:
        description: 'PHP extensions to install'
        required: false
        type: string
        default: 'bz2, ctype, curl, dom, fileinfo, gd, iconv, intl, json, libxml, mbstring, openssl, pcntl, posix, session, simplexml, xmlreader, xmlwriter, zip, zlib, sqlite, pdo_sqlite'
      path-filters:
        description: 'Paths to filter on (YAML format)'
        required: false
        type: string
        default: |
          - '**.php'
          - '.php-cs-fixer.dist.php'

permissions:
  pull-requests: read
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      src: ${{ steps.changes.outputs.src }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build filters
        id: build-filters
        run: |
          echo "yaml<<EOF" >> $GITHUB_OUTPUT
          echo "src:" >> $GITHUB_OUTPUT
          echo '${{ inputs.path-filters }}' | sed 's/^/  /' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - uses: dorny/paths-filter@v3
        id: changes
        continue-on-error: true
        with:
          filters: ${{ steps.build-filters.outputs.yaml }}

  lint:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.src == 'true'

    name: php-cs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get php version
        id: versions
        uses: icewind1991/nextcloud-version-matrix@v1

      - name: Set up php${{ steps.versions.outputs.php-available }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ steps.versions.outputs.php-available }}
          extensions: ${{ inputs.php-extensions }}
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer i

      - name: Lint
        run: ${{ inputs.cs-check-command }}

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [changes, lint]

    if: always()

    name: php-cs-summary

    steps:
      - name: Summary status
        run: if ${{ needs.changes.outputs.src == 'true' && needs.lint.result != 'success' }}; then exit 1; fi
