# Reusable workflow for Nextcloud appinfo.xml linting
#
# SPDX-FileCopyrightText: 2022-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Lint appinfo.xml

on:
  workflow_call:
    inputs:
      xml-file:
        description: 'Path to the info.xml file'
        required: false
        type: string
        default: './appinfo/info.xml'
      schema-url:
        description: 'URL to the XSD schema file'
        required: false
        type: string
        default: 'https://raw.githubusercontent.com/nextcloud/appstore/master/nextcloudappstore/api/v1/release/info.xsd'
      path-filters:
        description: 'Paths to filter on (YAML format)'
        required: false
        type: string
        default: |
          - 'appinfo/info.xml'

permissions:
  pull-requests: read
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      src: ${{ steps.changes.outputs.src }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              ${{ inputs.path-filters }}

  xml-linters:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.src != 'false'

    name: info.xml lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download schema
        run: wget ${{ inputs.schema-url }} -O info.xsd

      - name: Lint info.xml
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ${{ inputs.xml-file }}
          xml-schema-file: ./info.xsd

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [changes, xml-linters]

    if: always()

    name: appinfo-xml-summary

    steps:
      - name: Summary status
        run: if ${{ needs.changes.outputs.src != 'false' && needs.xml-linters.result != 'success' }}; then exit 1; fi
